### ISSUE TITLE
Bitmap font produces white png

### ISSUE THREAD

**Issue by ncannasse** [Yanrishatum/fontgen#5]
```
[
	{
	  "input": "04B_03__.TTF",
	  "output": "font20.fnt",
	  "mode": "raster",
	  "options": ["fixwinding", "allownonprint"],
	  "charset": [
		"latin", "latin1 supplement"
	  ],
	  "fontSize": 14
	}
]
```

TTF can be found here: https://github.com/ncannasse/ld24/blob/master/gfx/04B_03__.TTF

**Comment by Yanrishatum** [comment]
Which software you use to look at png files? :) Trethaller had same issue with XNView not displaying A8R8 png files correctly.

**Comment by ncannasse** [comment]
Ah, might be xnview fault indeed :D will recheck

**Comment by ncannasse** [comment]
Could we have an option for PNG8 instead ? (0 = transparent)

**Comment by Yanrishatum** [comment]
I'm not sure. Currently format is picked automatically by underlying `lodepng` library that `msdfgen` uses, but I had plans to delve deeper into png generation, see #3

**Comment by ncannasse** [comment]
Right, the PNG works. However there seems to be some kind of dithering while it should be a Bitmap Font

**Comment by Yanrishatum** [comment]
Dithering is due to fontSize. 04B03 is 8px font, and 8px/16px look adequate, hence 14px font would cause it to get antialiased.

**Comment by trethaller** [comment]
This is fixed by https://github.com/Yanrishatum/fontgen/commit/825ab3c09947a45ab198b54c181a917fc557030f
